### ISSUE TITLE
Click on the chat created by `New Chat`, but no websocket connection is established.

### ISSUE THREAD

**Issue by vegetablest** [edwardzjl/chatbot#26]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

* Click on the chat created by `New Chat` at the top, but no websocket connection is established.

## Actual behavior
* No websocket connection created
* There will be a websocket connection after refreshing the page

## Expected behavior

* Create a websocket connection and answer my questions

**Comment by edwardzjl** [comment]
Currently chatbot maintains one websocket for all conversations of an user, so that is expected behaviour.

**Comment by vegetablest** [comment]
But sometimes there is no response when asking a question in a new conversation。
<img width="1245" alt="image" src="https://github.com/edwardzjl/chatbot/assets/53895794/71777965-1ccf-4e1c-80ef-eec5fac38b10">

**Comment by edwardzjl** [comment]
Interesting, I will dive into this later.

**Comment by edwardzjl** [comment]
It seems `_acall` is not entered, but the result was correctly generated and saved into the history, weird.
